//*****************************************
// Author: Steve Cirelli
// File Desc: 
//*****************************************

if( scUtils === undefined ) var scUtils = new Object();

;!function( scUtils ){
"use strict";
    scUtils.MimeType = function( sName, sMimeType, sFileExtension, sDetails ){
        this.sName          = sName;
        this.sMimeType      = sMimeType;
        this.sFileExtension = sFileExtension;
        this.sDetails       = sDetails;
    }

    scUtils.MimeTypes = function(){
        this.aImages = [
            new scUtils.MimeType('Arista Networks Software Image', 'application/vnd.aristanetworks.swi', '.swi', 'IANA: Arista Networks Software Image'),
            new scUtils.MimeType('OpenDocument Image','application/vnd.oasis.opendocument.image','.odi','IANA: OpenDocument Image'),
            new scUtils.MimeType('OpenDocument Image Template','application/vnd.oasis.opendocument.image-template','.oti','IANA: OpenDocument Image Template'),
            new scUtils.MimeType('Princeton Video Image','application/vnd.pvi.ptid1','.ptid','IANA: Princeton Video Image'),
            new scUtils.MimeType('Bitmap Image File','image/bmp','.bmp','Wikipedia: BMP File Format'),
            new scUtils.MimeType('Computer Graphics Metafile','image/cgm','.cgm','Wikipedia: Computer Graphics Metafile'),
            new scUtils.MimeType('G3 Fax Image','image/g3fax','.g3','Wikipedia: G3 Fax Image'),
            new scUtils.MimeType('Graphics Interchange Format','image/gif','.gif','Wikipedia: Graphics Interchange Format'),
            new scUtils.MimeType('Image Exchange Format','image/ief','.ief','RFC 1314'),
            new scUtils.MimeType('JPEG Image','image/jpeg','.jpeg, .jpg','RFC 1314'),
            new scUtils.MimeType('OpenGL Textures (KTX)','image/ktx','.ktx','KTX File Format'),
            new scUtils.MimeType('Portable Network Graphics (PNG)','image/png','.png','RFC 2083'),
            new scUtils.MimeType('BTIF','image/prs.btif','.btif','IANA: BTIF'),
            new scUtils.MimeType('Scalable Vector Graphics (SVG)','image/svg+xml','.svg','Wikipedia: SVG'),
            new scUtils.MimeType('Tagged Image File Format','image/tiff','.tiff','Wikipedia: TIFF'),
            new scUtils.MimeType('Photoshop Document','image/vnd.adobe.photoshop','.psd','Wikipedia: Photoshop Document'),
            new scUtils.MimeType('DECE Graphic','image/vnd.dece.graphic','.uvi','IANA: DECE Graphic'),
            new scUtils.MimeType('DjVu','image/vnd.djvu','.djvu','Wikipedia: DjVu'),
            new scUtils.MimeType('Close Captioning - Subtitle','image/vnd.dvb.subtitle','.sub','Wikipedia: Closed Captioning'),
            new scUtils.MimeType('DWG Drawing','image/vnd.dwg','.dwg','Wikipedia: DWG'),
            new scUtils.MimeType('AutoCAD DXF','image/vnd.dxf','.dxf','Wikipedia: AutoCAD DXF'),
            new scUtils.MimeType('FastBid Sheet','image/vnd.fastbidsheet','.fbs','IANA: FastBid Sheet'),
            new scUtils.MimeType('FlashPix','image/vnd.fpx','.fpx','IANA: FPX'),
            new scUtils.MimeType('FAST Search & Transfer ASA','image/vnd.fst','.fst','IANA: FAST Search & Transfer ASA'),
            new scUtils.MimeType('EDMICS 2000','image/vnd.fujixerox.edmics-mmr','.mmr','IANA: EDMICS 2000'),
            new scUtils.MimeType('EDMICS 2000','image/vnd.fujixerox.edmics-rlc','.rlc','IANA: EDMICS 2000'),
            new scUtils.MimeType('Microsoft Document Imaging Format','image/vnd.ms-modi','.mdi','Wikipedia: Microsoft Document Image Format'),
            new scUtils.MimeType('FlashPix','image/vnd.net-fpx','.npx','IANA: FPX'),
            new scUtils.MimeType('WAP Bitamp (WBMP)','image/vnd.wap.wbmp','.wbmp','IANA: WBMP'),
            new scUtils.MimeType('eXtended Image File Format (XIFF)','image/vnd.xiff','.xif','IANA: XIFF'),
            new scUtils.MimeType('WebP Image','image/webp','.webp','Wikipedia: WebP'),
            new scUtils.MimeType('CMU Image','image/x-cmu-raster','.ras',''),
            new scUtils.MimeType('Corel Metafile Exchange (CMX)','image/x-cmx','.cmx','Wikipedia: CorelDRAW'),
            new scUtils.MimeType('FreeHand MX','image/x-freehand','.fh','Wikipedia: Macromedia Freehand'),
            new scUtils.MimeType('Icon Image','image/x-icon','.ico','Wikipedia: ICO File Format'),
            new scUtils.MimeType('PCX Image','image/x-pcx','.pcx','Wikipedia: PCX'),
            new scUtils.MimeType('PICT Image','image/x-pict','.pic','Wikipedia: PICT'),
            new scUtils.MimeType('Portable Anymap Image','image/x-portable-anymap','.pnm','Wikipedia: Netpbm Format'),
            new scUtils.MimeType('Portable Bitmap Format','image/x-portable-bitmap','.pbm','Wikipedia: Netpbm Format'),
            new scUtils.MimeType('Portable Graymap Format','image/x-portable-graymap','.pgm','Wikipedia: Netpbm Format'),
            new scUtils.MimeType('Portable Pixmap Format','image/x-portable-pixmap','.ppm','Wikipedia: Netpbm Format'),
            new scUtils.MimeType('Silicon Graphics RGB Bitmap','image/x-rgb','.rgb','RGB Image Format'),
            new scUtils.MimeType('X BitMap','image/x-xbitmap','.xbm','Wikipedia: X BitMap'),
            new scUtils.MimeType('X PixMap','image/x-xpixmap','.xpm','Wikipedia: X PixMap'),
            new scUtils.MimeType('X Window Dump','image/x-xwindowdump','.xwd','Wikipedia: X Window Dump')
        ];
        this.aText = [
            new scUtils.MimeType('iCalendar','text/calendar','.ics','Wikipedia: iCalendar'),
            new scUtils.MimeType('Cascading Style Sheets (CSS)','text/css','.css','Wikipedia: CSS'),
            new scUtils.MimeType('Comma-Seperated Values','text/csv','.csv','Wikipedia: CSV'),
            new scUtils.MimeType('HyperText Markup Language (HTML)','text/html','.html','Wikipedia: HTML'),
            new scUtils.MimeType('Notation3','text/n3','.n3','Wikipedia: Notation3'),
            new scUtils.MimeType('Text File','text/plain','.txt','Wikipedia: Text File'),
            new scUtils.MimeType('BAS Partitur Format','text/plain-bas','.par','Phonetik BAS'),
            new scUtils.MimeType('PRS Lines Tag','text/prs.lines.tag','.dsc','IANA: PRS Lines Tag'),
            new scUtils.MimeType('Rich Text Format (RTF)','text/richtext','.rtx','Wikipedia: Rich Text Format'),
            new scUtils.MimeType('Standard Generalized Markup Language (SGML)','text/sgml','.sgml','Wikipedia: SGML'),
            new scUtils.MimeType('Tab Seperated Values','text/tab-separated-values','.tsv','Wikipedia: TSV'),
            new scUtils.MimeType('troff','text/troff','.t','Wikipedia: troff'),
            new scUtils.MimeType('Turtle (Terse RDF Triple Language)','text/turtle','.ttl','Wikipedia: Turtle'),
            new scUtils.MimeType('URI Resolution Services','text/uri-list','.uri','RFC 2483'),
            new scUtils.MimeType('Curl - Applet','text/vnd.curl','.curl','Curl Applet'),
            new scUtils.MimeType('Curl - Detached Applet','text/vnd.curl.dcurl','.dcurl','Curl Detached Applet'),
            new scUtils.MimeType('Curl - Manifest File','text/vnd.curl.mcurl','.mcurl','Curl Manifest File'),
            new scUtils.MimeType('Curl - Source Code','text/vnd.curl.scurl','.scurl','Curl Source Code'),
            new scUtils.MimeType('mod_fly / fly.cgi','text/vnd.fly','.fly','IANA: Fly'),
            new scUtils.MimeType('FLEXSTOR','text/vnd.fmi.flexstor','.flx','IANA: FLEXSTOR'),
            new scUtils.MimeType('Graphviz','text/vnd.graphviz','.gv','IANA: Graphviz'),
            new scUtils.MimeType('In3D - 3DML','text/vnd.in3d.3dml','.3dml','IANA: In3D'),
            new scUtils.MimeType('In3D - 3DML','text/vnd.in3d.spot','.spot','IANA: In3D'),
            new scUtils.MimeType('J2ME App Descriptor','text/vnd.sun.j2me.app-descriptor','.jad','IANA: J2ME App Descriptor'),
            new scUtils.MimeType('Wireless Markup Language (WML)','text/vnd.wap.wml','.wml','Wikipedia: WML'),
            new scUtils.MimeType('Wireless Markup Language Script (WMLScript)','text/vnd.wap.wmlscript','.wmls','Wikipedia: WMLScript'),
            new scUtils.MimeType('Assembler Source File','text/x-asm','.s','Wikipedia: Assembly'),
            new scUtils.MimeType('C Source File','text/x-c','.c','Wikipedia: C Programming Language'),
            new scUtils.MimeType('Fortran Source File','text/x-fortran','.f','Wikipedia: Fortran'),
            new scUtils.MimeType('Java Source File','text/x-java-source,java','.java','Wikipedia: Java'),
            new scUtils.MimeType('Pascal Source File','text/x-pascal','.p','Wikipedia: Pascal'),
            new scUtils.MimeType('Setext','text/x-setext','.etx','Wikipedia: Setext'),
            new scUtils.MimeType('UUEncode','text/x-uuencode','.uu','Wikipedia: UUEncode'),
            new scUtils.MimeType('vCalendar','text/x-vcalendar','.vcs','Wikipedia: vCalendar'),
            new scUtils.MimeType('vCard','text/x-vcard','.vcf','Wikipedia: vCard')
        ];
        this.aApplication = [
            new scUtils.MimeType('Andrew Toolkit','application/andrew-inset','N/A','IANA - Andrew Inset'),
            new scUtils.MimeType('Applixware','application/applixware','.aw','Vistasource'),
            new scUtils.MimeType('Atom Syndication Format','application/atom+xml','.atom, .xml','RFC 4287'),
            new scUtils.MimeType('Atom Publishing Protocol','application/atomcat+xml','.atomcat','RFC 5023'),
            new scUtils.MimeType('Atom Publishing Protocol Service Document','application/atomsvc+xml','.atomsvc','RFC 5023'),
            new scUtils.MimeType('Voice Browser Call Control','application/ccxml+xml,','.ccxml','Voice Browser Call Control: CCXML Version 1.0'),
            new scUtils.MimeType('Cloud Data Management Interface (CDMI) - Capability','application/cdmi-capability','.cdmia','RFC 6208'),
            new scUtils.MimeType('Cloud Data Management Interface (CDMI) - Contaimer','application/cdmi-container','.cdmic','RFC 6209'),
            new scUtils.MimeType('Cloud Data Management Interface (CDMI) - Domain','application/cdmi-domain','.cdmid','RFC 6210'),
            new scUtils.MimeType('Cloud Data Management Interface (CDMI) - Object','application/cdmi-object','.cdmio','RFC 6211'),
            new scUtils.MimeType('Cloud Data Management Interface (CDMI) - Queue','application/cdmi-queue','.cdmiq','RFC 6212'),
            new scUtils.MimeType('CU-SeeMe','application/cu-seeme','.cu','White Pine'),
            new scUtils.MimeType('Web Distributed Authoring and Versioning','application/davmount+xml','.davmount','RFC 4918'),
            new scUtils.MimeType('Data Structure for the Security Suitability of Cryptographic Algorithms','application/dssc+der','.dssc','RFC 5698'),
            new scUtils.MimeType('Data Structure for the Security Suitability of Cryptographic Algorithms','application/dssc+xml','.xdssc','RFC 5698'),
            new scUtils.MimeType('ECMAScript','application/ecmascript','.es','ECMA-357'),
            new scUtils.MimeType('Extensible MultiModal Annotation','application/emma+xml','.emma','EMMA: Extensible MultiModal Annotation markup language'),
            new scUtils.MimeType('Electronic Publication','application/epub+zip','.epub','Wikipedia: EPUB'),
            new scUtils.MimeType('Efficient XML Interchange','application/exi','.exi','Efficient XML Interchange (EXI) Best Practices'),
            new scUtils.MimeType('Portable Font Resource','application/font-tdpfr','.pfr','RFC 3073'),
            new scUtils.MimeType('Hyperstudio','application/hyperstudio','.stk','IANA - Hyperstudio'),
            new scUtils.MimeType('Internet Protocol Flow Information Export','application/ipfix','.ipfix','RFC 3917'),
            new scUtils.MimeType('Java Archive','application/java-archive','.jar','Wikipedia: JAR file format'),
            new scUtils.MimeType('Java Serialized Object','application/java-serialized-object','.ser','Java Serialization API'),
            new scUtils.MimeType('Java Bytecode File','application/java-vm','.class','Wikipedia: Java Bytecode'),
            new scUtils.MimeType('JavaScript','application/javascript','.js','JavaScript'),
            new scUtils.MimeType('JavaScript Object Notation (JSON)','application/json','.json','Wikipedia: JSON'),
            new scUtils.MimeType('Macintosh BinHex 4.0','application/mac-binhex40','.hqx','MacMIME'),
            new scUtils.MimeType('Compact Pro','application/mac-compactpro','.cpt','Compact Pro'),
            new scUtils.MimeType('Metadata Authority Description Schema','application/mads+xml','.mads','RFC 6207'),
            new scUtils.MimeType('MARC Formats','application/marc','.mrc','RFC 2220'),
            new scUtils.MimeType('MARC21 XML Schema','application/marcxml+xml','.mrcx','RFC 6207'),
            new scUtils.MimeType('Mathematica Notebooks','application/mathematica','.ma','IANA - Mathematica'),
            new scUtils.MimeType('Mathematical Markup Language','application/mathml+xml','.mathml','W3C Math Home'),
            new scUtils.MimeType('Mbox database files','application/mbox','.mbox','RFC 4155'),
            new scUtils.MimeType('Media Server Control Markup Language','application/mediaservercontrol+xml','.mscml','RFC 5022'),
            new scUtils.MimeType('Metalink','application/metalink4+xml','.meta4','Wikipedia: Metalink'),
            new scUtils.MimeType('Metadata Encoding and Transmission Standard','application/mets+xml','.mets','RFC 6207'),
            new scUtils.MimeType('Metadata Object Description Schema','application/mods+xml','.mods','RFC 6207'),
            new scUtils.MimeType('MPEG-21','application/mp21','.m21','Wikipedia: MPEG-21'),
            new scUtils.MimeType('MPEG4','application/mp4','.mp4','RFC 4337'),
            new scUtils.MimeType('Microsoft Word','application/msword','.doc','Wikipedia: Microsoft Word'),
            new scUtils.MimeType('Material Exchange Format','application/mxf','.mxf','RFC 4539'),
            new scUtils.MimeType('Binary Data','application/octet-stream','.bin',''),
            new scUtils.MimeType('Office Document Architecture','application/oda','.oda','RFC 2161'),
            new scUtils.MimeType('Open eBook Publication Structure','application/oebps-package+xml','.opf','Wikipedia: Open eBook'),
            new scUtils.MimeType('Ogg','application/ogg','.ogx','Wikipedia: Ogg'),
            new scUtils.MimeType('Microsoft OneNote','application/onenote','.onetoc','MS OneNote 2010'),
            new scUtils.MimeType('XML Patch Framework','application/patch-ops-error+xml','.xer','RFC 5261'),
            new scUtils.MimeType('Adobe Portable Document Format','application/pdf','.pdf','Adobe PDF'),
            new scUtils.MimeType('Pretty Good Privacy','application/pgp-encrypted','','RFC 2015'),
            new scUtils.MimeType('Pretty Good Privacy - Signature','application/pgp-signature','.pgp','RFC 2015'),
            new scUtils.MimeType('PICSRules','application/pics-rules','.prf','W3C PICSRules'),
            new scUtils.MimeType('PKCS #10 - Certification Request Standard','application/pkcs10','.p10','RFC 2986'),
            new scUtils.MimeType('PKCS #7 - Cryptographic Message Syntax Standard','application/pkcs7-mime','.p7m','RFC 2315'),
            new scUtils.MimeType('PKCS #7 - Cryptographic Message Syntax Standard','application/pkcs7-signature','.p7s','RFC 2315'),
            new scUtils.MimeType('PKCS #8 - Private-Key Information Syntax Standard','application/pkcs8','.p8','RFC 5208'),
            new scUtils.MimeType('Attribute Certificate','application/pkix-attr-cert','.ac','RFC 5877'),
            new scUtils.MimeType('Internet Public Key Infrastructure - Certificate','application/pkix-cert','.cer','RFC 2585'),
            new scUtils.MimeType('Internet Public Key Infrastructure - Certificate Revocation Lists','application/pkix-crl','.crl','RFC 2585'),
            new scUtils.MimeType('Internet Public Key Infrastructure - Certification Path','application/pkix-pkipath','.pkipath','RFC 2585'),
            new scUtils.MimeType('Internet Public Key Infrastructure - Certificate Management Protocole','application/pkixcmp','.pki','RFC 2585'),
            new scUtils.MimeType('Pronunciation Lexicon Specification','application/pls+xml','.pls','RFC 4267'),
            new scUtils.MimeType('PostScript','application/postscript','.ai','Wikipedia: PostScript'),
            new scUtils.MimeType('CU-Writer','application/prs.cww','.cww',''),
            new scUtils.MimeType('Portable Symmetric Key Container','application/pskc+xml','.pskcxml','RFC 6030'),
            new scUtils.MimeType('Resource Description Framework','application/rdf+xml','.rdf','RFC 3870'),
            new scUtils.MimeType('IMS Networks','application/reginfo+xml','.rif',''),
            new scUtils.MimeType('Relax NG Compact Syntax','application/relax-ng-compact-syntax','.rnc','Relax NG'),
            new scUtils.MimeType('XML Resource Lists','application/resource-lists+xml','.rl','RFC 4826'),
            new scUtils.MimeType('XML Resource Lists Diff','application/resource-lists-diff+xml','.rld','RFC 4826'),
            new scUtils.MimeType('XML Resource Lists','application/rls-services+xml','.rs','RFC 4826'),
            new scUtils.MimeType('Really Simple Discovery','application/rsd+xml','.rsd','Wikipedia: Really Simple Discovery'),
            new scUtils.MimeType('RSS - Really Simple Syndication','application/rss+xml','.rss, .xml','Wikipedia: RSS'),
            new scUtils.MimeType('Rich Text Format','application/rtf','.rtf','Wikipedia: Rich Text Format'),
            new scUtils.MimeType('Systems Biology Markup Language','application/sbml+xml','.sbml','RFC 3823'),
            new scUtils.MimeType('Server-Based Certificate Validation Protocol - Validation Request','application/scvp-cv-request','.scq','RFC 5055'),
            new scUtils.MimeType('Server-Based Certificate Validation Protocol - Validation Response','application/scvp-cv-response','.scs','RFC 5055'),
            new scUtils.MimeType('Server-Based Certificate Validation Protocol - Validation Policies - Request','application/scvp-vp-request','.spq','RFC 5055'),
            new scUtils.MimeType('Server-Based Certificate Validation Protocol - Validation Policies - Response','application/scvp-vp-response','.spp','RFC 5055'),
            new scUtils.MimeType('Session Description Protocol','application/sdp','.sdp','RFC 2327'),
            new scUtils.MimeType('Secure Electronic Transaction - Payment','application/set-payment-initiation','.setpay','IANA: SET Payment'),
            new scUtils.MimeType('Secure Electronic Transaction - Registration','application/set-registration-initiation','.setreg','IANA: SET Registration'),
            new scUtils.MimeType('S Hexdump Format','application/shf+xml','.shf','RFC 4194'),
            new scUtils.MimeType('Synchronized Multimedia Integration Language','application/smil+xml','.smi','RFC 4536'),
            new scUtils.MimeType('SPARQL - Query','application/sparql-query','.rq','W3C SPARQL'),
            new scUtils.MimeType('SPARQL - Results','application/sparql-results+xml','.srx','W3C SPARQL'),
            new scUtils.MimeType('Speech Recognition Grammar Specification','application/srgs','.gram','W3C Speech Grammar'),
            new scUtils.MimeType('Speech Recognition Grammar Specification - XML','application/srgs+xml','.grxml','W3C Speech Grammar'),
            new scUtils.MimeType('Search/Retrieve via URL Response Format','application/sru+xml','.sru','RFC 6207'),
            new scUtils.MimeType('Speech Synthesis Markup Language','application/ssml+xml','.ssml','W3C Speech Synthesis'),
            new scUtils.MimeType('Text Encoding and Interchange','application/tei+xml','.tei','RFC 6129'),
            new scUtils.MimeType('Sharing Transaction Fraud Data','application/thraud+xml','.tfi','RFC 5941'),
            new scUtils.MimeType('Time Stamped Data Envelope','application/timestamped-data','.tsd','RFC 5955'),
            new scUtils.MimeType('3rd Generation Partnership Project - Pic Large','application/vnd.3gpp.pic-bw-large','.plb','3GPP'),
            new scUtils.MimeType('3rd Generation Partnership Project - Pic Small','application/vnd.3gpp.pic-bw-small','.psb','3GPP'),
            new scUtils.MimeType('3rd Generation Partnership Project - Pic Var','application/vnd.3gpp.pic-bw-var','.pvb','3GPP'),
            new scUtils.MimeType('3rd Generation Partnership Project - Transaction Capabilities Application Part','application/vnd.3gpp2.tcap','.tcap','3GPP'),
            new scUtils.MimeType('3M Post It Notes','application/vnd.3m.post-it-notes','.pwn','IANA: 3M Post It Notes'),
            new scUtils.MimeType('Simply Accounting','application/vnd.accpac.simply.aso','.aso','IANA: Simply Accounting'),
            new scUtils.MimeType('Simply Accounting - Data Import','application/vnd.accpac.simply.imp','.imp','IANA: Simply Accounting'),
            new scUtils.MimeType('ACU Cobol','application/vnd.acucobol','.acu','IANA: ACU Cobol'),
            new scUtils.MimeType('ACU Cobol','application/vnd.acucorp','.atc','IANA: ACU Cobol'),
            new scUtils.MimeType('Adobe AIR Application','application/vnd.adobe.air-application-installer-package+zip','.air','Building AIR Applications'),
            new scUtils.MimeType('Adobe Flex Project','application/vnd.adobe.fxp','.fxp','IANA: Adobe Flex Project'),
            new scUtils.MimeType('Adobe XML Data Package','application/vnd.adobe.xdp+xml','.xdp','Wikipedia: XML Data Package'),
            new scUtils.MimeType('Adobe XML Forms Data Format','application/vnd.adobe.xfdf','.xfdf','Wikipedia: XML Portable Document Format'),
            new scUtils.MimeType('Ahead AIR Application','application/vnd.ahead.space','.ahead','IANA: Ahead AIR Application'),
            new scUtils.MimeType('AirZip FileSECURE','application/vnd.airzip.filesecure.azf','.azf','IANA: AirZip'),
            new scUtils.MimeType('AirZip FileSECURE','application/vnd.airzip.filesecure.azs','.azs','IANA: AirZip'),
            new scUtils.MimeType('Amazon Kindle eBook format','application/vnd.amazon.ebook','.azw','Kindle Direct Publishing'),
            new scUtils.MimeType('Active Content Compression','application/vnd.americandynamics.acc','.acc','IANA: Active Content Compression'),
            new scUtils.MimeType('AmigaDE','application/vnd.amiga.ami','.ami','IANA: Amiga'),
            new scUtils.MimeType('Android Package Archive','application/vnd.android.package-archive','.apk','Wikipedia: APK File Format'),
            new scUtils.MimeType('ANSER-WEB Terminal Client - Certificate Issue','application/vnd.anser-web-certificate-issue-initiation','.cii','IANA: ANSWER-WEB'),
            new scUtils.MimeType('ANSER-WEB Terminal Client - Web Funds Transfer','application/vnd.anser-web-funds-transfer-initiation','.fti','IANA: ANSWER-WEB'),
            new scUtils.MimeType('Antix Game Player','application/vnd.antix.game-component','.atx','IANA: Antix Game Component'),
            new scUtils.MimeType('Apple Installer Package','application/vnd.apple.installer+xml','.mpkg','IANA: Apple Installer'),
            new scUtils.MimeType('Multimedia Playlist Unicode','application/vnd.apple.mpegurl','.m3u8','Wikipedia: M3U'),
            new scUtils.MimeType('Arista Networks Software Image','application/vnd.aristanetworks.swi','.swi','IANA: Arista Networks Software Image'),
            new scUtils.MimeType('Audiograph','application/vnd.audiograph','.aep','IANA: Audiograph'),
            new scUtils.MimeType('Blueice Research Multipass','application/vnd.blueice.multipass','.mpm','IANA: Multipass'),
            new scUtils.MimeType('BMI Drawing Data Interchange','application/vnd.bmi','.bmi','IANA: BMI'),
            new scUtils.MimeType('BusinessObjects','application/vnd.businessobjects','.rep','IANA: BusinessObjects'),
            new scUtils.MimeType('CambridgeSoft Chem Draw','application/vnd.chemdraw+xml','.cdxml','IANA: Chem Draw'),
            new scUtils.MimeType('Karaoke on Chipnuts Chipsets','application/vnd.chipnuts.karaoke-mmd','.mmd','IANA: Chipnuts Karaoke'),
            new scUtils.MimeType('Interactive Geometry Software Cinderella','application/vnd.cinderella','.cdy','IANA: Cinderella'),
            new scUtils.MimeType('Claymore Data Files','application/vnd.claymore','.cla','IANA: Claymore'),
            new scUtils.MimeType('RetroPlatform Player','application/vnd.cloanto.rp9','.rp9','IANA: RetroPlatform Player'),
            new scUtils.MimeType('Clonk Game','application/vnd.clonk.c4group','.c4g','IANA: Clonk'),
            new scUtils.MimeType('ClueTrust CartoMobile - Config','application/vnd.cluetrust.cartomobile-config','.c11amc','IANA: CartoMobile'),
            new scUtils.MimeType('ClueTrust CartoMobile - Config Package','application/vnd.cluetrust.cartomobile-config-pkg','.c11amz','IANA: CartoMobile'),
            new scUtils.MimeType('Sixth Floor Media - CommonSpace','application/vnd.commonspace','.csp','IANA: CommonSpace'),
            new scUtils.MimeType('CIM Database','application/vnd.contact.cmsg','.cdbcmsg','IANA: CIM Database'),
            new scUtils.MimeType('CosmoCaller','application/vnd.cosmocaller','.cmc','IANA: CosmoCaller'),
            new scUtils.MimeType('CrickSoftware - Clicker','application/vnd.crick.clicker','.clkx','IANA: Clicker'),
            new scUtils.MimeType('CrickSoftware - Clicker - Keyboard','application/vnd.crick.clicker.keyboard','.clkk','IANA: Clicker'),
            new scUtils.MimeType('CrickSoftware - Clicker - Palette','application/vnd.crick.clicker.palette','.clkp','IANA: Clicker'),
            new scUtils.MimeType('CrickSoftware - Clicker - Template','application/vnd.crick.clicker.template','.clkt','IANA: Clicker'),
            new scUtils.MimeType('CrickSoftware - Clicker - Wordbank','application/vnd.crick.clicker.wordbank','.clkw','IANA: Clicker'),
            new scUtils.MimeType('Critical Tools - PERT Chart EXPERT','application/vnd.criticaltools.wbs+xml','.wbs','IANA: Critical Tools'),
            new scUtils.MimeType('PosML','application/vnd.ctc-posml','.pml','IANA: PosML'),
            new scUtils.MimeType('Adobe PostScript Printer Description File Format','application/vnd.cups-ppd','.ppd','IANA: Cups'),
            new scUtils.MimeType('CURL Applet','application/vnd.curl.car','.car','IANA: CURL Applet'),
            new scUtils.MimeType('CURL Applet','application/vnd.curl.pcurl','.pcurl','IANA: CURL Applet'),
            new scUtils.MimeType('RemoteDocs R-Viewer','application/vnd.data-vision.rdz','.rdz','IANA: Data-Vision'),
            new scUtils.MimeType('FCS Express Layout Link','application/vnd.denovo.fcselayout-link','.fe_launch','IANA: FCS Express Layout Link'),
            new scUtils.MimeType('New Moon Liftoff/DNA','application/vnd.dna','.dna','IANA: New Moon Liftoff/DNA'),
            new scUtils.MimeType('Dolby Meridian Lossless Packing','application/vnd.dolby.mlp','.mlp','IANA: Dolby Meridian Lossless Packing'),
            new scUtils.MimeType('DPGraph','application/vnd.dpgraph','.dpg','IANA: DPGraph'),
            new scUtils.MimeType('DreamFactory','application/vnd.dreamfactory','.dfac','IANA: DreamFactory'),
            new scUtils.MimeType('Digital Video Broadcasting','application/vnd.dvb.ait','.ait','IANA: Digital Video Broadcasting'),
            new scUtils.MimeType('Digital Video Broadcasting','application/vnd.dvb.service','.svc','IANA: Digital Video Broadcasting'),
            new scUtils.MimeType('DynaGeo','application/vnd.dynageo','.geo','IANA: DynaGeo'),
            new scUtils.MimeType('EcoWin Chart','application/vnd.ecowin.chart','.mag','IANA: EcoWin Chart'),
            new scUtils.MimeType('Enliven Viewer','application/vnd.enliven','.nml','IANA: Enliven Viewer'),
            new scUtils.MimeType('QUASS Stream Player','application/vnd.epson.esf','.esf','IANA: QUASS Stream Player'),
            new scUtils.MimeType('QUASS Stream Player','application/vnd.epson.msf','.msf','IANA: QUASS Stream Player'),
            new scUtils.MimeType('QuickAnime Player','application/vnd.epson.quickanime','.qam','IANA: QuickAnime Player'),
            new scUtils.MimeType('SimpleAnimeLite Player','application/vnd.epson.salt','.slt','IANA: SimpleAnimeLite Player'),
            new scUtils.MimeType('QUASS Stream Player','application/vnd.epson.ssf','.ssf','IANA: QUASS Stream Player'),
            new scUtils.MimeType('MICROSEC e-Szign¢','application/vnd.eszigno3+xml','.es3','IANA: MICROSEC e-Szign¢'),
            new scUtils.MimeType('EZPix Secure Photo Album','application/vnd.ezpix-album','.ez2','IANA: EZPix Secure Photo Album'),
            new scUtils.MimeType('EZPix Secure Photo Album','application/vnd.ezpix-package','.ez3','IANA: EZPix Secure Photo Album'),
            new scUtils.MimeType('Forms Data Format','application/vnd.fdf','.fdf','IANA: Forms Data Format'),
            new scUtils.MimeType('Digital Siesmograph Networks - SEED Datafiles','application/vnd.fdsn.seed','.seed','IANA: SEED'),
            new scUtils.MimeType('NpGraphIt','application/vnd.flographit','.gph','IANA: FloGraphIt'),
            new scUtils.MimeType('FluxTime Clip','application/vnd.fluxtime.clip','.ftc','IANA: FluxTime Clip'),
            new scUtils.MimeType('FrameMaker Normal Format','application/vnd.framemaker','.fm','IANA: FrameMaker'),
            new scUtils.MimeType('Frogans Player','application/vnd.frogans.fnc','.fnc','IANA: Frogans Player'),
            new scUtils.MimeType('Frogans Player','application/vnd.frogans.ltf','.ltf','IANA: Frogans Player'),
            new scUtils.MimeType('Friendly Software Corporation','application/vnd.fsc.weblaunch','.fsc','IANA: Friendly Software Corporation'),
            new scUtils.MimeType('Fujitsu Oasys','application/vnd.fujitsu.oasys','.oas','IANA: Fujitsu Oasys'),
            new scUtils.MimeType('Fujitsu Oasys','application/vnd.fujitsu.oasys2','.oa2','IANA: Fujitsu Oasys'),
            new scUtils.MimeType('Fujitsu Oasys','application/vnd.fujitsu.oasys3','.oa3','IANA: Fujitsu Oasys'),
            new scUtils.MimeType('Fujitsu Oasys','application/vnd.fujitsu.oasysgp','.fg5','IANA: Fujitsu Oasys'),
            new scUtils.MimeType('Fujitsu Oasys','application/vnd.fujitsu.oasysprs','.bh2','IANA: Fujitsu Oasys'),
            new scUtils.MimeType('Fujitsu - Xerox 2D CAD Data','application/vnd.fujixerox.ddd','.ddd','IANA: Fujitsu DDD'),
            new scUtils.MimeType('Fujitsu - Xerox DocuWorks','application/vnd.fujixerox.docuworks','.xdw','IANA: Docuworks'),
            new scUtils.MimeType('Fujitsu - Xerox DocuWorks Binder','application/vnd.fujixerox.docuworks.binder','.xbd','IANA: Docuworks Binder'),
            new scUtils.MimeType('FuzzySheet','application/vnd.fuzzysheet','.fzs','IANA: FuzySheet'),
            new scUtils.MimeType('Genomatix Tuxedo Framework','application/vnd.genomatix.tuxedo','.txd','IANA: Genomatix Tuxedo Framework'),
            new scUtils.MimeType('GeoGebra','application/vnd.geogebra.file','.ggb','IANA: GeoGebra'),
            new scUtils.MimeType('GeoGebra','application/vnd.geogebra.tool','.ggt','IANA: GeoGebra'),
            new scUtils.MimeType('GeoMetry Explorer','application/vnd.geometry-explorer','.gex','IANA: GeoMetry Explorer'),
            new scUtils.MimeType('GEONExT and JSXGraph','application/vnd.geonext','.gxt','IANA: GEONExT and JSXGraph'),
            new scUtils.MimeType('GeoplanW','application/vnd.geoplan','.g2w','IANA: GeoplanW'),
            new scUtils.MimeType('GeospacW','application/vnd.geospace','.g3w','IANA: GeospacW'),
            new scUtils.MimeType('GameMaker ActiveX','application/vnd.gmx','.gmx','IANA: GameMaker ActiveX'),
            new scUtils.MimeType('Google Earth - KML','application/vnd.google-earth.kml+xml','.kml','IANA: Google Earth'),
            new scUtils.MimeType('Google Earth - Zipped KML','application/vnd.google-earth.kmz','.kmz','IANA: Google Earth'),
            new scUtils.MimeType('GrafEq','application/vnd.grafeq','.gqf','IANA: GrafEq'),
            new scUtils.MimeType('Groove - Account','application/vnd.groove-account','.gac','IANA: Groove'),
            new scUtils.MimeType('Groove - Help','application/vnd.groove-help','.ghf','IANA: Groove'),
            new scUtils.MimeType('Groove - Identity Message','application/vnd.groove-identity-message','.gim','IANA: Groove'),
            new scUtils.MimeType('Groove - Injector','application/vnd.groove-injector','.grv','IANA: Groove'),
            new scUtils.MimeType('Groove - Tool Message','application/vnd.groove-tool-message','.gtm','IANA: Groove'),
            new scUtils.MimeType('Groove - Tool Template','application/vnd.groove-tool-template','.tpl','IANA: Groove'),
            new scUtils.MimeType('Groove - Vcard','application/vnd.groove-vcard','.vcg','IANA: Groove'),
            new scUtils.MimeType('Hypertext Application Language','application/vnd.hal+xml','.hal','IANA: HAL'),
            new scUtils.MimeType('ZVUE Media Manager','application/vnd.handheld-entertainment+xml','.zmm','IANA: ZVUE Media Manager'),
            new scUtils.MimeType('Homebanking Computer Interface (HBCI)','application/vnd.hbci','.hbci','IANA: HBCI'),
            new scUtils.MimeType('Archipelago Lesson Player','application/vnd.hhe.lesson-player','.les','IANA: Archipelago Lesson Player'),
            new scUtils.MimeType('HP-GL/2 and HP RTL','application/vnd.hp-hpgl','.hpgl','IANA: HP-GL/2 and HP RTL'),
            new scUtils.MimeType('Hewlett Packard Instant Delivery','application/vnd.hp-hpid','.hpid','IANA: Hewlett Packard Instant Delivery'),
            new scUtils.MimeType('Hewlett-Packard\'s WebPrintSmart','application/vnd.hp-hps','.hps','IANA: Hewlett-Packard\'s WebPrintSmart'),
            new scUtils.MimeType('HP Indigo Digital Press - Job Layout Languate','application/vnd.hp-jlyt','.jlt','IANA: HP Job Layout Language'),
            new scUtils.MimeType('HP Printer Command Language','application/vnd.hp-pcl','.pcl','IANA: HP Printer Command Language'),
            new scUtils.MimeType('PCL 6 Enhanced (Formely PCL XL)','application/vnd.hp-pclxl','.pclxl','IANA: HP PCL XL'),
            new scUtils.MimeType('Hydrostatix Master Suite','application/vnd.hydrostatix.sof-data','.sfd-hdstx','IANA: Hydrostatix Master Suite'),
            new scUtils.MimeType('3D Crossword Plugin','application/vnd.hzn-3d-crossword','.x3d','IANA: 3D Crossword Plugin'),
            new scUtils.MimeType('MiniPay','application/vnd.ibm.minipay','.mpy','IANA: MiniPay'),
            new scUtils.MimeType('MO:DCA-P','application/vnd.ibm.modcap','.afp','IANA: MO:DCA-P'),
            new scUtils.MimeType('IBM DB2 Rights Manager','application/vnd.ibm.rights-management','.irm','IANA: IBM DB2 Rights Manager'),
            new scUtils.MimeType('IBM Electronic Media Management System - Secure Container','application/vnd.ibm.secure-container','.sc','IANA: EMMS'),
            new scUtils.MimeType('ICC profile','application/vnd.iccprofile','.icc','IANA: ICC profile'),
            new scUtils.MimeType('igLoader','application/vnd.igloader','.igl','IANA: igLoader'),
            new scUtils.MimeType('ImmerVision PURE Players','application/vnd.immervision-ivp','.ivp','IANA: ImmerVision PURE Players'),
            new scUtils.MimeType('ImmerVision PURE Players','application/vnd.immervision-ivu','.ivu','IANA: ImmerVision PURE Players'),
            new scUtils.MimeType('IOCOM Visimeet','application/vnd.insors.igm','.igm','IANA: IOCOM Visimeet'),
            new scUtils.MimeType('Intercon FormNet','application/vnd.intercon.formnet','.xpw','IANA: Intercon FormNet'),
            new scUtils.MimeType('Interactive Geometry Software','application/vnd.intergeo','.i2g','IANA: Interactive Geometry Software'),
            new scUtils.MimeType('Open Financial Exchange','application/vnd.intu.qbo','.qbo','IANA: Open Financial Exchange'),
            new scUtils.MimeType('Quicken','application/vnd.intu.qfx','.qfx','IANA: Quicken'),
            new scUtils.MimeType('IP Unplugged Roaming Client','application/vnd.ipunplugged.rcprofile','.rcprofile','IANA: IP Unplugged Roaming Client'),
            new scUtils.MimeType('iRepository / Lucidoc Editor','application/vnd.irepository.package+xml','.irp','IANA: iRepository / Lucidoc Editor'),
            new scUtils.MimeType('Express by Infoseek','application/vnd.is-xpr','.xpr','IANA: Express by Infoseek'),
            new scUtils.MimeType('International Society for Advancement of Cytometry','application/vnd.isac.fcs','.fcs','IANA: International Society for Advancement of Cytometry'),
            new scUtils.MimeType('Lightspeed Audio Lab','application/vnd.jam','.jam','IANA: Lightspeed Audio Lab'),
            new scUtils.MimeType('Mobile Information Device Profile','application/vnd.jcp.javame.midlet-rms','.rms','IANA: Mobile Information Device Profile'),
            new scUtils.MimeType('RhymBox','application/vnd.jisp','.jisp','IANA: RhymBox'),
            new scUtils.MimeType('Joda Archive','application/vnd.joost.joda-archive','.joda','IANA: Joda Archive'),
            new scUtils.MimeType('Kahootz','application/vnd.kahootz','.ktz','IANA: Kahootz'),
            new scUtils.MimeType('KDE KOffice Office Suite - Karbon','application/vnd.kde.karbon','.karbon','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - KChart','application/vnd.kde.kchart','.chrt','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - Kformula','application/vnd.kde.kformula','.kfo','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - Kivio','application/vnd.kde.kivio','.flw','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - Kontour','application/vnd.kde.kontour','.kon','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - Kpresenter','application/vnd.kde.kpresenter','.kpr','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - Kspread','application/vnd.kde.kspread','.ksp','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('KDE KOffice Office Suite - Kword','application/vnd.kde.kword','.kwd','IANA: KDE KOffice Office Suite'),
            new scUtils.MimeType('Kenamea App','application/vnd.kenameaapp','.htke','IANA: Kenamea App'),
            new scUtils.MimeType('Kidspiration','application/vnd.kidspiration','.kia','IANA: Kidspiration'),
            new scUtils.MimeType('Kinar Applications','application/vnd.kinar','.kne','IANA: Kina Applications'),
            new scUtils.MimeType('SSEYO Koan Play File','application/vnd.koan','.skp','IANA: SSEYO Koan Play File'),
            new scUtils.MimeType('Kodak Storyshare','application/vnd.kodak-descriptor','.sse','IANA: Kodak Storyshare'),
            new scUtils.MimeType('Laser App Enterprise','application/vnd.las.las+xml','.lasxml','IANA: Laser App Enterprise'),
            new scUtils.MimeType('Life Balance - Desktop Edition','application/vnd.llamagraphics.life-balance.desktop','.lbd','IANA: Life Balance'),
            new scUtils.MimeType('Life Balance - Exchange Format','application/vnd.llamagraphics.life-balance.exchange+xml','.lbe','IANA: Life Balance'),
            new scUtils.MimeType('Lotus 1-2-3','application/vnd.lotus-1-2-3','.123','IANA: Lotus 1-2-3'),
            new scUtils.MimeType('Lotus Approach','application/vnd.lotus-approach','.apr','IANA: Lotus Approach'),
            new scUtils.MimeType('Lotus Freelance','application/vnd.lotus-freelance','.pre','IANA: Lotus Freelance'),
            new scUtils.MimeType('Lotus Notes','application/vnd.lotus-notes','.nsf','IANA: Lotus Notes'),
            new scUtils.MimeType('Lotus Organizer','application/vnd.lotus-organizer','.org','IANA: Lotus Organizer'),
            new scUtils.MimeType('Lotus Screencam','application/vnd.lotus-screencam','.scm','IANA: Lotus Screencam'),
            new scUtils.MimeType('Lotus Wordpro','application/vnd.lotus-wordpro','.lwp','IANA: Lotus Wordpro'),
            new scUtils.MimeType('MacPorts Port System','application/vnd.macports.portpkg','.portpkg','IANA: MacPorts Port System'),
            new scUtils.MimeType('Micro CADAM Helix D&D','application/vnd.mcd','.mcd','IANA: Micro CADAM Helix D&D'),
            new scUtils.MimeType('MedCalc','application/vnd.medcalcdata','.mc1','IANA: MedCalc'),
            new scUtils.MimeType('MediaRemote','application/vnd.mediastation.cdkey','.cdkey','IANA: MediaRemote'),
            new scUtils.MimeType('Medical Waveform Encoding Format','application/vnd.mfer','.mwf','IANA: Medical Waveform Encoding Format'),
            new scUtils.MimeType('Melody Format for Mobile Platform','application/vnd.mfmp','.mfm','IANA: Melody Format for Mobile Platform'),
            new scUtils.MimeType('Micrografx','application/vnd.micrografx.flo','.flo','IANA: Micrografx'),
            new scUtils.MimeType('Micrografx iGrafx Professional','application/vnd.micrografx.igx','.igx','IANA: Micrografx'),
            new scUtils.MimeType('FrameMaker Interchange Format','application/vnd.mif','.mif','IANA: FrameMaker Interchange Format'),
            new scUtils.MimeType('Mobius Management Systems - UniversalArchive','application/vnd.mobius.daf','.daf','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mobius Management Systems - Distribution Database','application/vnd.mobius.dis','.dis','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mobius Management Systems - Basket file','application/vnd.mobius.mbk','.mbk','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mobius Management Systems - Query File','application/vnd.mobius.mqy','.mqy','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mobius Management Systems - Script Language','application/vnd.mobius.msl','.msl','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mobius Management Systems - Policy Definition Language File','application/vnd.mobius.plc','.plc','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mobius Management Systems - Topic Index File','application/vnd.mobius.txf','.txf','IANA: Mobius Management Systems'),
            new scUtils.MimeType('Mophun VM','application/vnd.mophun.application','.mpn','IANA: Mophun VM'),
            new scUtils.MimeType('Mophun Certificate','application/vnd.mophun.certificate','.mpc','IANA: Mophun Certificate'),
            new scUtils.MimeType('XUL - XML User Interface Language','application/vnd.mozilla.xul+xml','.xul','IANA: XUL'),
            new scUtils.MimeType('Microsoft Artgalry','application/vnd.ms-artgalry','.cil','IANA: MS Artgalry'),
            new scUtils.MimeType('Microsoft Cabinet File','application/vnd.ms-cab-compressed','.cab','IANA: MS Cabinet File'),
            new scUtils.MimeType('Microsoft Excel','application/vnd.ms-excel','.xls','IANA: MS Excel'),
            new scUtils.MimeType('Microsoft Excel - Add-In File','application/vnd.ms-excel.addin.macroenabled.12','.xlam','IANA: MS Excel'),
            new scUtils.MimeType('Microsoft Excel - Binary Workbook','application/vnd.ms-excel.sheet.binary.macroenabled.12','.xlsb','IANA: MS Excel'),
            new scUtils.MimeType('Microsoft Excel - Macro-Enabled Workbook','application/vnd.ms-excel.sheet.macroenabled.12','.xlsm','IANA: MS Excel'),
            new scUtils.MimeType('Microsoft Excel - Macro-Enabled Template File','application/vnd.ms-excel.template.macroenabled.12','.xltm','IANA: MS Excel'),
            new scUtils.MimeType('Microsoft Embedded OpenType','application/vnd.ms-fontobject','.eot','IANA: MS Embedded OpenType'),
            new scUtils.MimeType('Microsoft Html Help File','application/vnd.ms-htmlhelp','.chm','IANA:MS Html Help File'),
            new scUtils.MimeType('Microsoft Class Server','application/vnd.ms-ims','.ims','IANA: MS Class Server'),
            new scUtils.MimeType('Microsoft Learning Resource Module','application/vnd.ms-lrm','.lrm','IANA: MS Learning Resource Module'),
            new scUtils.MimeType('Microsoft Office System Release Theme','application/vnd.ms-officetheme','.thmx','IANA: MS Office System Release Theme'),
            new scUtils.MimeType('Microsoft Trust UI Provider - Security Catalog','application/vnd.ms-pki.seccat','.cat','IANA: MS Trust UI Provider'),
            new scUtils.MimeType('Microsoft Trust UI Provider - Certificate Trust Link','application/vnd.ms-pki.stl','.stl','IANA: MS Trust UI Provider'),
            new scUtils.MimeType('Microsoft PowerPoint','application/vnd.ms-powerpoint','.ppt','IANA: MS PowerPoint'),
            new scUtils.MimeType('Microsoft PowerPoint - Add-in file','application/vnd.ms-powerpoint.addin.macroenabled.12','.ppam','IANA: MS PowerPoint'),
            new scUtils.MimeType('Microsoft PowerPoint - Macro-Enabled Presentation File','application/vnd.ms-powerpoint.presentation.macroenabled.12','.pptm','IANA: MS PowerPoint'),
            new scUtils.MimeType('Microsoft PowerPoint - Macro-Enabled Open XML Slide','application/vnd.ms-powerpoint.slide.macroenabled.12','.sldm','IANA: MS PowerPoint'),
            new scUtils.MimeType('Microsoft PowerPoint - Macro-Enabled Slide Show File','application/vnd.ms-powerpoint.slideshow.macroenabled.12','.ppsm','IANA: MS PowerPoint'),
            new scUtils.MimeType('Micosoft PowerPoint - Macro-Enabled Template File','application/vnd.ms-powerpoint.template.macroenabled.12','.potm','IANA: MS PowerPoint'),
            new scUtils.MimeType('Microsoft Project','application/vnd.ms-project','.mpp','IANA: MS PowerPoint'),
            new scUtils.MimeType('Micosoft Word - Macro-Enabled Document','application/vnd.ms-word.document.macroenabled.12','.docm','IANA: MS Word'),
            new scUtils.MimeType('Micosoft Word - Macro-Enabled Template','application/vnd.ms-word.template.macroenabled.12','.dotm','IANA: MS Word'),
            new scUtils.MimeType('Microsoft Works','application/vnd.ms-works','.wps','IANA: MS Works'),
            new scUtils.MimeType('Microsoft Windows Media Player Playlist','application/vnd.ms-wpl','.wpl','IANA: MS Windows Media Player Playlist'),
            new scUtils.MimeType('Microsoft XML Paper Specification','application/vnd.ms-xpsdocument','.xps','IANA: MS XML Paper Specification'),
            new scUtils.MimeType('3GPP MSEQ File','application/vnd.mseq','.mseq','IANA: 3GPP MSEQ File'),
            new scUtils.MimeType('MUsical Score Interpreted Code Invented for the ASCII designation of Notation','application/vnd.musician','.mus','IANA: MUSICIAN'),
            new scUtils.MimeType('Muvee Automatic Video Editing','application/vnd.muvee.style','.msty','IANA: Muvee'),
            new scUtils.MimeType('neuroLanguage','application/vnd.neurolanguage.nlu','.nlu','IANA: neuroLanguage'),
            new scUtils.MimeType('NobleNet Directory','application/vnd.noblenet-directory','.nnd','IANA: NobleNet Directory'),
            new scUtils.MimeType('NobleNet Sealer','application/vnd.noblenet-sealer','.nns','IANA: NobleNet Sealer'),
            new scUtils.MimeType('NobleNet Web','application/vnd.noblenet-web','.nnw','IANA: NobleNet Web'),
            new scUtils.MimeType('N-Gage Game Data','application/vnd.nokia.n-gage.data','.ngdat','IANA: N-Gage Game Data'),
            new scUtils.MimeType('N-Gage Game Installer','application/vnd.nokia.n-gage.symbian.install','.n-gage','IANA: N-Gage Game Installer'),
            new scUtils.MimeType('Nokia Radio Application - Preset','application/vnd.nokia.radio-preset','.rpst','IANA: Nokia Radio Application'),
            new scUtils.MimeType('Nokia Radio Application - Preset','application/vnd.nokia.radio-presets','.rpss','IANA: Nokia Radio Application'),
            new scUtils.MimeType('Novadigm\'s RADIA and EDM products','application/vnd.novadigm.edm','.edm','IANA: Novadigm\'s RADIA and EDM products'),
            new scUtils.MimeType('Novadigm\'s RADIA and EDM products','application/vnd.novadigm.edx','.edx','IANA: Novadigm\'s RADIA and EDM products'),
            new scUtils.MimeType('Novadigm\'s RADIA and EDM products','application/vnd.novadigm.ext','.ext','IANA: Novadigm\'s RADIA and EDM products'),
            new scUtils.MimeType('OpenDocument Chart','application/vnd.oasis.opendocument.chart','.odc','IANA: OpenDocument Chart'),
            new scUtils.MimeType('OpenDocument Chart Template','application/vnd.oasis.opendocument.chart-template','.otc','IANA: OpenDocument Chart Template'),
            new scUtils.MimeType('OpenDocument Database','application/vnd.oasis.opendocument.database','.odb','IANA: OpenDocument Database'),
            new scUtils.MimeType('OpenDocument Formula','application/vnd.oasis.opendocument.formula','.odf','IANA: OpenDocument Formula'),
            new scUtils.MimeType('OpenDocument Formula Template','application/vnd.oasis.opendocument.formula-template','.odft','IANA: OpenDocument Formula Template'),
            new scUtils.MimeType('OpenDocument Graphics','application/vnd.oasis.opendocument.graphics','.odg','IANA: OpenDocument Graphics'),
            new scUtils.MimeType('OpenDocument Graphics Template','application/vnd.oasis.opendocument.graphics-template','.otg','IANA: OpenDocument Graphics Template'),
            new scUtils.MimeType('OpenDocument Image','application/vnd.oasis.opendocument.image','.odi','IANA: OpenDocument Image'),
            new scUtils.MimeType('OpenDocument Image Template','application/vnd.oasis.opendocument.image-template','.oti','IANA: OpenDocument Image Template'),
            new scUtils.MimeType('OpenDocument Presentation','application/vnd.oasis.opendocument.presentation','.odp','IANA: OpenDocument Presentation'),
            new scUtils.MimeType('OpenDocument Presentation Template','application/vnd.oasis.opendocument.presentation-template','.otp','IANA: OpenDocument Presentation Template'),
            new scUtils.MimeType('OpenDocument Spreadsheet','application/vnd.oasis.opendocument.spreadsheet','.ods','IANA: OpenDocument Spreadsheet'),
            new scUtils.MimeType('OpenDocument Spreadsheet Template','application/vnd.oasis.opendocument.spreadsheet-template','.ots','IANA: OpenDocument Spreadsheet Template'),
            new scUtils.MimeType('OpenDocument Text','application/vnd.oasis.opendocument.text','.odt','IANA: OpenDocument Text'),
            new scUtils.MimeType('OpenDocument Text Master','application/vnd.oasis.opendocument.text-master','.odm','IANA: OpenDocument Text Master'),
            new scUtils.MimeType('OpenDocument Text Template','application/vnd.oasis.opendocument.text-template','.ott','IANA: OpenDocument Text Template'),
            new scUtils.MimeType('Open Document Text Web','application/vnd.oasis.opendocument.text-web','.oth','IANA: OpenDocument Text Web'),
            new scUtils.MimeType('Sugar Linux Application Bundle','application/vnd.olpc-sugar','.xo','IANA: Sugar Linux App Bundle'),
            new scUtils.MimeType('OMA Download Agents','application/vnd.oma.dd2+xml','.dd2','IANA: OMA Download Agents'),
            new scUtils.MimeType('Open Office Extension','application/vnd.openofficeorg.extension','.oxt','IANA: Open Office Extension'),
            new scUtils.MimeType('Microsoft Office - OOXML - Presentation','application/vnd.openxmlformats-officedocument.presentationml.presentation','.pptx','IANA: OOXML - Presentation'),
            new scUtils.MimeType('Microsoft Office - OOXML - Presentation (Slide)','application/vnd.openxmlformats-officedocument.presentationml.slide','.sldx','IANA: OOXML - Presentation'),
            new scUtils.MimeType('Microsoft Office - OOXML - Presentation (Slideshow)','application/vnd.openxmlformats-officedocument.presentationml.slideshow','.ppsx','IANA: OOXML - Presentation'),
            new scUtils.MimeType('Microsoft Office - OOXML - Presentation Template','application/vnd.openxmlformats-officedocument.presentationml.template','.potx','IANA: OOXML - Presentation Template'),
            new scUtils.MimeType('Microsoft Office - OOXML - Spreadsheet','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.xlsx','IANA: OOXML - Spreadsheet'),
            new scUtils.MimeType('Microsoft Office - OOXML - Spreadsheet Teplate','application/vnd.openxmlformats-officedocument.spreadsheetml.template','.xltx','IANA: OOXML - Spreadsheet Template'),
            new scUtils.MimeType('Microsoft Office - OOXML - Word Document','application/vnd.openxmlformats-officedocument.wordprocessingml.document','.docx','IANA: OOXML - Word Document'),
            new scUtils.MimeType('Microsoft Office - OOXML - Word Document Template','application/vnd.openxmlformats-officedocument.wordprocessingml.template','.dotx','IANA: OOXML - Word Document Template'),
            new scUtils.MimeType('MapGuide DBXML','application/vnd.osgeo.mapguide.package','.mgp','IANA: MapGuide DBXML'),
            new scUtils.MimeType('OSGi Deployment Package','application/vnd.osgi.dp','.dp','IANA: OSGi Deployment Package'),
            new scUtils.MimeType('PalmOS Data','application/vnd.palm','.pdb','IANA: PalmOS Data'),
            new scUtils.MimeType('PawaaFILE','application/vnd.pawaafile','.paw','IANA: PawaaFILE'),
            new scUtils.MimeType('Proprietary P&G Standard Reporting System','application/vnd.pg.format','.str','IANA: Proprietary P&G Standard Reporting System'),
            new scUtils.MimeType('Proprietary P&G Standard Reporting System','application/vnd.pg.osasli','.ei6','IANA: Proprietary P&G Standard Reporting System'),
            new scUtils.MimeType('Pcsel eFIF File','application/vnd.picsel','.efif','IANA: Picsel eFIF File'),
            new scUtils.MimeType('Qualcomm\'s Plaza Mobile Internet','application/vnd.pmi.widget','.wg','IANA: Qualcomm\'s Plaza Mobile Internet'),
            new scUtils.MimeType('PocketLearn Viewers','application/vnd.pocketlearn','.plf','IANA: PocketLearn Viewers'),
            new scUtils.MimeType('PowerBuilder','application/vnd.powerbuilder6','.pbd','IANA: PowerBuilder'),
            new scUtils.MimeType('Preview Systems ZipLock/VBox','application/vnd.previewsystems.box','.box','IANA: Preview Systems ZipLock/Vbox'),
            new scUtils.MimeType('EFI Proteus','application/vnd.proteus.magazine','.mgz','IANA: EFI Proteus'),
            new scUtils.MimeType('PubliShare Objects','application/vnd.publishare-delta-tree','.qps','IANA: PubliShare Objects'),
            new scUtils.MimeType('Princeton Video Image','application/vnd.pvi.ptid1','.ptid','IANA: Princeton Video Image'),
            new scUtils.MimeType('QuarkXpress','application/vnd.quark.quarkxpress','.qxd','IANA: QuarkXPress'),
            new scUtils.MimeType('RealVNC','application/vnd.realvnc.bed','.bed','IANA: RealVNC'),
            new scUtils.MimeType('Recordare Applications','application/vnd.recordare.musicxml','.mxl','IANA: Recordare Apps'),
            new scUtils.MimeType('Recordare Applications','application/vnd.recordare.musicxml+xml','.musicxml','IANA: Recordare Apps'),
            new scUtils.MimeType('CryptoNote','application/vnd.rig.cryptonote','.cryptonote','IANA: CryptoNote'),
            new scUtils.MimeType('Blackberry COD File','application/vnd.rim.cod','.cod',''),
            new scUtils.MimeType('RealMedia','application/vnd.rn-realmedia','.rm',''),
            new scUtils.MimeType('ROUTE 66 Location Based Services','application/vnd.route66.link66+xml','.link66','IANA: ROUTE 66'),
            new scUtils.MimeType('SailingTracker','application/vnd.sailingtracker.track','.st','IANA: SailingTracker'),
            new scUtils.MimeType('SeeMail','application/vnd.seemail','.see','IANA: SeeMail'),
            new scUtils.MimeType('Secured eMail','application/vnd.sema','.sema','IANA: Secured eMail'),
            new scUtils.MimeType('Secured eMail','application/vnd.semd','.semd','IANA: Secured eMail'),
            new scUtils.MimeType('Secured eMail','application/vnd.semf','.semf','IANA: Secured eMail'),
            new scUtils.MimeType('Shana Informed Filler','application/vnd.shana.informed.formdata','.ifm','IANA: Shana Informed Filler'),
            new scUtils.MimeType('Shana Informed Filler','application/vnd.shana.informed.formtemplate','.itp','IANA: Shana Informed Filler'),
            new scUtils.MimeType('Shana Informed Filler','application/vnd.shana.informed.interchange','.iif','IANA: Shana Informed Filler'),
            new scUtils.MimeType('Shana Informed Filler','application/vnd.shana.informed.package','.ipk','IANA: Shana Informed Filler'),
            new scUtils.MimeType('SimTech MindMapper','application/vnd.simtech-mindmapper','.twd','IANA: SimTech MindMapper'),
            new scUtils.MimeType('SMAF File','application/vnd.smaf','.mmf','IANA: SMAF File'),
            new scUtils.MimeType('SMART Technologies Apps','application/vnd.smart.teacher','.teacher','IANA: SMART Technologies Apps'),
            new scUtils.MimeType('SudokuMagic','application/vnd.solent.sdkm+xml','.sdkm','IANA: SudokuMagic'),
            new scUtils.MimeType('TIBCO Spotfire','application/vnd.spotfire.dxp','.dxp','IANA: TIBCO Spotfire'),
            new scUtils.MimeType('TIBCO Spotfire','application/vnd.spotfire.sfs','.sfs','IANA: TIBCO Spotfire'),
            new scUtils.MimeType('StarOffice - Calc','application/vnd.stardivision.calc','.sdc',''),
            new scUtils.MimeType('StarOffice - Draw','application/vnd.stardivision.draw','.sda',''),
            new scUtils.MimeType('StarOffice - Impress','application/vnd.stardivision.impress','.sdd',''),
            new scUtils.MimeType('StarOffice - Math','application/vnd.stardivision.math','.smf',''),
            new scUtils.MimeType('StarOffice - Writer','application/vnd.stardivision.writer','.sdw',''),
            new scUtils.MimeType('StarOffice - Writer (Global)','application/vnd.stardivision.writer-global','.sgl',''),
            new scUtils.MimeType('StepMania','application/vnd.stepmania.stepchart','.sm','IANA: StepMania'),
            new scUtils.MimeType('OpenOffice - Calc (Spreadsheet)','application/vnd.sun.xml.calc','.sxc','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Calc Template (Spreadsheet)','application/vnd.sun.xml.calc.template','.stc','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Draw (Graphics)','application/vnd.sun.xml.draw','.sxd','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Draw Template (Graphics)','application/vnd.sun.xml.draw.template','.std','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Impress (Presentation)','application/vnd.sun.xml.impress','.sxi','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Impress Template (Presentation)','application/vnd.sun.xml.impress.template','.sti','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Math (Formula)','application/vnd.sun.xml.math','.sxm','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Writer (Text - HTML)','application/vnd.sun.xml.writer','.sxw','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Writer (Text - HTML)','application/vnd.sun.xml.writer.global','.sxg','Wikipedia: OpenOffice'),
            new scUtils.MimeType('OpenOffice - Writer Template (Text - HTML)','application/vnd.sun.xml.writer.template','.stw','Wikipedia: OpenOffice'),
            new scUtils.MimeType('ScheduleUs','application/vnd.sus-calendar','.sus','IANA: ScheduleUs'),
            new scUtils.MimeType('SourceView Document','application/vnd.svd','.svd','IANA: SourceView Document'),
            new scUtils.MimeType('Symbian Install Package','application/vnd.symbian.install','.sis','IANA: Symbian Install'),
            new scUtils.MimeType('SyncML','application/vnd.syncml+xml','.xsm','IANA: SyncML'),
            new scUtils.MimeType('SyncML - Device Management','application/vnd.syncml.dm+wbxml','.bdm','IANA: SyncML'),
            new scUtils.MimeType('SyncML - Device Management','application/vnd.syncml.dm+xml','.xdm','IANA: SyncML'),
            new scUtils.MimeType('Tao Intent','application/vnd.tao.intent-module-archive','.tao','IANA: Tao Intent'),
            new scUtils.MimeType('MobileTV','application/vnd.tmobile-livetv','.tmo','IANA: MobileTV'),
            new scUtils.MimeType('TRI Systems Config','application/vnd.trid.tpt','.tpt','IANA: TRI Systems'),
            new scUtils.MimeType('Triscape Map Explorer','application/vnd.triscape.mxs','.mxs','IANA: Triscape Map Explorer'),
            new scUtils.MimeType('True BASIC','application/vnd.trueapp','.tra','IANA: True BASIC'),
            new scUtils.MimeType('Universal Forms Description Language','application/vnd.ufdl','.ufd','IANA: Universal Forms Description Language'),
            new scUtils.MimeType('User Interface Quartz - Theme (Symbian)','application/vnd.uiq.theme','.utz','IANA: User Interface Quartz'),
            new scUtils.MimeType('UMAJIN','application/vnd.umajin','.umj','IANA: UMAJIN'),
            new scUtils.MimeType('Unity 3d','application/vnd.unity','.unityweb','IANA: Unity 3d'),
            new scUtils.MimeType('Unique Object Markup Language','application/vnd.uoml+xml','.uoml','IANA: UOML'),
            new scUtils.MimeType('VirtualCatalog','application/vnd.vcx','.vcx','IANA: VirtualCatalog'),
            new scUtils.MimeType('Microsoft Visio','application/vnd.visio','.vsd','IANA: Visio'),
            new scUtils.MimeType('Visionary','application/vnd.visionary','.vis','IANA: Visionary'),
            new scUtils.MimeType('Viewport+','application/vnd.vsf','.vsf','IANA: Viewport+'),
            new scUtils.MimeType('WAP Binary XML (WBXML)','application/vnd.wap.wbxml','.wbxml','IANA: WBXML'),
            new scUtils.MimeType('Compiled Wireless Markup Language (WMLC)','application/vnd.wap.wmlc','.wmlc','IANA: WMLC'),
            new scUtils.MimeType('WMLScript','application/vnd.wap.wmlscriptc','.wmlsc','IANA: WMLScript'),
            new scUtils.MimeType('WebTurbo','application/vnd.webturbo','.wtb','IANA: WebTurbo'),
            new scUtils.MimeType('Mathematica Notebook Player','application/vnd.wolfram.player','.nbp','IANA: Mathematica Notebook Player'),
            new scUtils.MimeType('Wordperfect','application/vnd.wordperfect','.wpd','IANA: Wordperfect'),
            new scUtils.MimeType('SundaHus WQ','application/vnd.wqd','.wqd','IANA: SundaHus WQ'),
            new scUtils.MimeType('Worldtalk','application/vnd.wt.stf','.stf','IANA: Worldtalk'),
            new scUtils.MimeType('CorelXARA','application/vnd.xara','.xar','IANA: CorelXARA'),
            new scUtils.MimeType('Extensible Forms Description Language','application/vnd.xfdl','.xfdl','IANA: Extensible Forms Description Language'),
            new scUtils.MimeType('HV Voice Dictionary','application/vnd.yamaha.hv-dic','.hvd','IANA: HV Voice Dictionary'),
            new scUtils.MimeType('HV Script','application/vnd.yamaha.hv-script','.hvs','IANA: HV Script'),
            new scUtils.MimeType('HV Voice Parameter','application/vnd.yamaha.hv-voice','.hvp','IANA: HV Voice Parameter'),
            new scUtils.MimeType('Open Score Format','application/vnd.yamaha.openscoreformat','.osf','IANA: Open Score Format'),
            new scUtils.MimeType('OSFPVG','application/vnd.yamaha.openscoreformat.osfpvg+xml','.osfpvg','IANA: OSFPVG'),
            new scUtils.MimeType('SMAF Audio','application/vnd.yamaha.smaf-audio','.saf','IANA: SMAF Audio'),
            new scUtils.MimeType('SMAF Phrase','application/vnd.yamaha.smaf-phrase','.spf','IANA: SMAF Phrase'),
            new scUtils.MimeType('CustomMenu','application/vnd.yellowriver-custom-menu','.cmp','IANA: CustomMenu'),
            new scUtils.MimeType('Z.U.L. Geometry','application/vnd.zul','.zir','IANA: Z.U.L.'),
            new scUtils.MimeType('Zzazz Deck','application/vnd.zzazz.deck+xml','.zaz','IANA: Zzazz'),
            new scUtils.MimeType('VoiceXML','application/voicexml+xml','.vxml','RFC 4267'),
            new scUtils.MimeType('Widget Packaging and XML Configuration','application/widget','.wgt','W3C Widget Packaging and XML Configuration'),
            new scUtils.MimeType('WinHelp','application/winhlp','.hlp','Wikipedia: WinHelp'),
            new scUtils.MimeType('WSDL - Web Services Description Language','application/wsdl+xml','.wsdl','W3C Web Service Description Language'),
            new scUtils.MimeType('Web Services Policy','application/wspolicy+xml','.wspolicy','W3C Web Services Policy'),
            new scUtils.MimeType('7-Zip','application/x-7z-compressed','.7z','Wikipedia: 7-Zip'),
            new scUtils.MimeType('AbiWord','application/x-abiword','.abw','Wikipedia: AbiWord'),
            new scUtils.MimeType('Ace Archive','application/x-ace-compressed','.ace','Wikipedia: ACE'),
            new scUtils.MimeType('Adobe (Macropedia) Authorware - Binary File','application/x-authorware-bin','.aab','Wikipedia: Authorware'),
            new scUtils.MimeType('Adobe (Macropedia) Authorware - Map','application/x-authorware-map','.aam','Wikipedia: Authorware'),
            new scUtils.MimeType('Adobe (Macropedia) Authorware - Segment File','application/x-authorware-seg','.aas','Wikipedia: Authorware'),
            new scUtils.MimeType('Binary CPIO Archive','application/x-bcpio','.bcpio','Wikipedia: cpio'),
            new scUtils.MimeType('BitTorrent','application/x-bittorrent','.torrent','Wikipedia: BitTorrent'),
            new scUtils.MimeType('Bzip Archive','application/x-bzip','.bz','Wikipedia: Bzip'),
            new scUtils.MimeType('Bzip2 Archive','application/x-bzip2','.bz2','Wikipedia: Bzip'),
            new scUtils.MimeType('Video CD','application/x-cdlink','.vcd','Wikipedia: Video CD'),
            new scUtils.MimeType('pIRCh','application/x-chat','.chat','Wikipedia: pIRCh'),
            new scUtils.MimeType('Portable Game Notation (Chess Games)','application/x-chess-pgn','.pgn','Wikipedia: Portable Game Notationb'),
            new scUtils.MimeType('CPIO Archive','application/x-cpio','.cpio','Wikipedia: cpio'),
            new scUtils.MimeType('C Shell Script','application/x-csh','.csh','Wikipedia: C Shell'),
            new scUtils.MimeType('Debian Package','application/x-debian-package','.deb','Wikipedia: Debian Package'),
            new scUtils.MimeType('Adobe Shockwave Player','application/x-director','.dir','Wikipedia: Adobe Shockwave Player'),
            new scUtils.MimeType('Doom Video Game','application/x-doom','.wad','Wikipedia: Doom WAD'),
            new scUtils.MimeType('Navigation Control file for XML (for ePub)','application/x-dtbncx+xml','.ncx','Wikipedia: EPUB'),
            new scUtils.MimeType('Digital Talking Book','application/x-dtbook+xml','.dtb','Wikipedia: EPUB'),
            new scUtils.MimeType('Digital Talking Book - Resource File','application/x-dtbresource+xml','.res','Digital Talking Book'),
            new scUtils.MimeType('Device Independent File Format (DVI)','application/x-dvi','.dvi','Wikipedia: DVI'),
            new scUtils.MimeType('Glyph Bitmap Distribution Format','application/x-font-bdf','.bdf','Wikipedia: Glyph Bitmap Distribution Format'),
            new scUtils.MimeType('Ghostscript Font','application/x-font-ghostscript','.gsf','Wikipedia: Ghostscript'),
            new scUtils.MimeType('PSF Fonts','application/x-font-linux-psf','.psf','PSF Fonts'),
            new scUtils.MimeType('OpenType Font File','application/x-font-otf','.otf','OpenType Font File'),
            new scUtils.MimeType('Portable Compiled Format','application/x-font-pcf','.pcf','Wikipedia: Portable Compiled Format'),
            new scUtils.MimeType('Server Normal Format','application/x-font-snf','.snf','Wikipedia: Server Normal Format'),
            new scUtils.MimeType('TrueType Font','application/x-font-ttf','.ttf','Wikipedia: TrueType'),
            new scUtils.MimeType('PostScript Fonts','application/x-font-type1','.pfa','Wikipedia: PostScript Fonts'),
            new scUtils.MimeType('Web Open Font Format','application/x-font-woff','.woff','Wikipedia: Web Open Font Format'),
            new scUtils.MimeType('FutureSplash Animator','application/x-futuresplash','.spl','Wikipedia: FutureSplash Animator'),
            new scUtils.MimeType('Gnumeric','application/x-gnumeric','.gnumeric','Wikipedia: Gnumeric'),
            new scUtils.MimeType('GNU Tar Files','application/x-gtar','.gtar','GNU Tar'),
            new scUtils.MimeType('Hierarchical Data Format','application/x-hdf','.hdf','Wikipedia: Hierarchical Data Format'),
            new scUtils.MimeType('Java Network Launching Protocol','application/x-java-jnlp-file','.jnlp','Wikipedia: Java Web Start'),
            new scUtils.MimeType('LaTeX','application/x-latex','.latex','Wikipedia: LaTeX'),
            new scUtils.MimeType('Mobipocket','application/x-mobipocket-ebook','.prc','Wikipedia: Mobipocket'),
            new scUtils.MimeType('Microsoft ClickOnce','application/x-ms-application','.application','Wikipedia: ClickOnce'),
            new scUtils.MimeType('Microsoft Windows Media Player Download Package','application/x-ms-wmd','.wmd','Wikipedia: Windows Media Player'),
            new scUtils.MimeType('Microsoft Windows Media Player Skin Package','application/x-ms-wmz','.wmz','Wikipedia: Windows Media Player'),
            new scUtils.MimeType('Microsoft XAML Browser Application','application/x-ms-xbap','.xbap','Wikipedia: XAML Browser'),
            new scUtils.MimeType('Microsoft Access','application/x-msaccess','.mdb','Wikipedia: Microsoft Access'),
            new scUtils.MimeType('Microsoft Office Binder','application/x-msbinder','.obd','Wikipedia: Microsoft Shared Tools'),
            new scUtils.MimeType('Microsoft Information Card','application/x-mscardfile','.crd','Wikipedia: Information Card'),
            new scUtils.MimeType('Microsoft Clipboard Clip','application/x-msclip','.clp','Wikipedia: Clipboard'),
            new scUtils.MimeType('Microsoft Application','application/x-msdownload','.exe','Wikipedia: EXE'),
            new scUtils.MimeType('Microsoft MediaView','application/x-msmediaview','.mvb','Windows Help'),
            new scUtils.MimeType('Microsoft Windows Metafile','application/x-msmetafile','.wmf','Wikipedia: Windows Metafile'),
            new scUtils.MimeType('Microsoft Money','application/x-msmoney','.mny','Wikipedia: Microsoft Money'),
            new scUtils.MimeType('Microsoft Publisher','application/x-mspublisher','.pub','Wikipedia: Microsoft Publisher'),
            new scUtils.MimeType('Microsoft Schedule+','application/x-msschedule','.scd','Wikipedia: Microsoft Schedule Plus'),
            new scUtils.MimeType('Microsoft Windows Terminal Services','application/x-msterminal','.trm','Wikipedia: Terminal Server'),
            new scUtils.MimeType('Microsoft Wordpad','application/x-mswrite','.wri','Wikipedia: Wordpad'),
            new scUtils.MimeType('Network Common Data Form (NetCDF)','application/x-netcdf','.nc','Wikipedia: NetCDF'),
            new scUtils.MimeType('PKCS #12 - Personal Information Exchange Syntax Standard','application/x-pkcs12','.p12','RFC 2986'),
            new scUtils.MimeType('PKCS #7 - Cryptographic Message Syntax Standard (Certificates)','application/x-pkcs7-certificates','.p7b','RFC 2986'),
            new scUtils.MimeType('PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)','application/x-pkcs7-certreqresp','.p7r','RFC 2986'),
            new scUtils.MimeType('RAR Archive','application/x-rar-compressed','.rar','Wikipedia: RAR'),
            new scUtils.MimeType('Bourne Shell Script','application/x-sh','.sh','Wikipedia: Bourne Shell'),
            new scUtils.MimeType('Shell Archive','application/x-shar','.shar','Wikipedia: Shell Archie'),
            new scUtils.MimeType('Adobe Flash','application/x-shockwave-flash','.swf','Wikipedia: Adobe Flash'),
            new scUtils.MimeType('Microsoft Silverlight','application/x-silverlight-app','.xap','Wikipedia: Silverlight'),
            new scUtils.MimeType('Stuffit Archive','application/x-stuffit','.sit','Wikipedia: Stuffit'),
            new scUtils.MimeType('Stuffit Archive','application/x-stuffitx','.sitx','Wikipedia: Stuffit'),
            new scUtils.MimeType('System V Release 4 CPIO Archive','application/x-sv4cpio','.sv4cpio','Wikipedia: pax'),
            new scUtils.MimeType('System V Release 4 CPIO Checksum Data','application/x-sv4crc','.sv4crc','Wikipedia: pax'),
            new scUtils.MimeType('Tar File (Tape Archive)','application/x-tar','.tar','Wikipedia: Tar'),
            new scUtils.MimeType('Tcl Script','application/x-tcl','.tcl','Wikipedia: Tcl'),
            new scUtils.MimeType('TeX','application/x-tex','.tex','Wikipedia: TeX'),
            new scUtils.MimeType('TeX Font Metric','application/x-tex-tfm','.tfm','Wikipedia: TeX Font Metric'),
            new scUtils.MimeType('GNU Texinfo Document','application/x-texinfo','.texinfo','Wikipedia: Texinfo'),
            new scUtils.MimeType('Ustar (Uniform Standard Tape Archive)','application/x-ustar','.ustar','Wikipedia: Ustar'),
            new scUtils.MimeType('WAIS Source','application/x-wais-source','.src','YoLinux'),
            new scUtils.MimeType('X.509 Certificate','application/x-x509-ca-cert','.der','Wikipedia: X.509'),
            new scUtils.MimeType('Xfig','application/x-xfig','.fig','Wikipedia: Xfig'),
            new scUtils.MimeType('XPInstall - Mozilla','application/x-xpinstall','.xpi','Wikipedia: XPI'),
            new scUtils.MimeType('XML Configuration Access Protocol - XCAP Diff','application/xcap-diff+xml','.xdf','Wikipedia: XCAP'),
            new scUtils.MimeType('XML Encryption Syntax and Processing','application/xenc+xml','.xenc','W3C XML Encryption Syntax and Processing'),
            new scUtils.MimeType('XHTML - The Extensible HyperText Markup Language','application/xhtml+xml','.xhtml','W3C XHTML'),
            new scUtils.MimeType('XML - Extensible Markup Language','application/xml','.xml','W3C XML'),
            new scUtils.MimeType('Document Type Definition','application/xml-dtd','.dtd','W3C DTD'),
            new scUtils.MimeType('XML-Binary Optimized Packaging','application/xop+xml','.xop','W3C XOP'),
            new scUtils.MimeType('XML Transformations','application/xslt+xml','.xslt','W3C XSLT'),
            new scUtils.MimeType('XSPF - XML Shareable Playlist Format','application/xspf+xml','.xspf','XML Shareable Playlist Format'),
            new scUtils.MimeType('MXML','application/xv+xml','.mxml','Wikipedia: MXML'),
            new scUtils.MimeType('YANG Data Modeling Language','application/yang','.yang','Wikipedia: YANG'),
            new scUtils.MimeType('YIN (YANG - XML)','application/yin+xml','.yin','Wikipedia: YANG'),
            new scUtils.MimeType('Zip Archive','application/zip','.zip','Wikipedia: Zip')
        ];
        this.aAudio = [
            new scUtils.MimeType('Adaptive differential pulse-code modulation','audio/adpcm','.adp','Wikipedia: ADPCM'),
            new scUtils.MimeType('Sun Audio - Au file format','audio/basic','.au','Wikipedia: Sun audio'),
            new scUtils.MimeType('MIDI - Musical Instrument Digital Interface','audio/midi','.mid','Wikipedia: MIDI'),
            new scUtils.MimeType('MPEG-4 Audio','audio/mp4','.mp4a','Wikipedia: MP4A'),
            new scUtils.MimeType('MPEG Audio','audio/mpeg','.mpga','Wikipedia: MPGA'),
            new scUtils.MimeType('Ogg Audio','audio/ogg','.oga','Wikipedia: Ogg'),
            new scUtils.MimeType('DECE Audio','audio/vnd.dece.audio','.uva','IANA: Dece Audio'),
            new scUtils.MimeType('Digital Winds Music','audio/vnd.digital-winds','.eol','IANA: Digital Winds'),
            new scUtils.MimeType('DRA Audio','audio/vnd.dra','.dra','IANA: DRA'),
            new scUtils.MimeType('DTS Audio','audio/vnd.dts','.dts','IANA: DTS'),
            new scUtils.MimeType('DTS High Definition Audio','audio/vnd.dts.hd','.dtshd','IANA: DTS HD'),
            new scUtils.MimeType('Lucent Voice','audio/vnd.lucent.voice','.lvp','IANA: Lucent Voice'),
            new scUtils.MimeType('Microsoft PlayReady Ecosystem','audio/vnd.ms-playready.media.pya','.pya','IANA: Microsoft PlayReady Ecosystem'),
            new scUtils.MimeType('Nuera ECELP 4800','audio/vnd.nuera.ecelp4800','.ecelp4800','IANA: ECELP 4800'),
            new scUtils.MimeType('Nuera ECELP 7470','audio/vnd.nuera.ecelp7470','.ecelp7470','IANA: ECELP 7470'),
            new scUtils.MimeType('Nuera ECELP 9600','audio/vnd.nuera.ecelp9600','.ecelp9600','IANA: ECELP 9600'),
            new scUtils.MimeType('Hit\'n\'Mix','audio/vnd.rip','.rip','IANA: Hit\'n\'Mix'),
            new scUtils.MimeType('Open Web Media Project - Audio','audio/webm','.weba','WebM Project'),
            new scUtils.MimeType('Advanced Audio Coding (AAC)','audio/x-aac','.aac','Wikipedia: AAC'),
            new scUtils.MimeType('Audio Interchange File Format','audio/x-aiff','.aif','Wikipedia: Audio Interchange File Format'),
            new scUtils.MimeType('M3U (Multimedia Playlist)','audio/x-mpegurl','.m3u','Wikipedia: M3U'),
            new scUtils.MimeType('Microsoft Windows Media Audio Redirector','audio/x-ms-wax','.wax','Windows Media Metafiles'),
            new scUtils.MimeType('Microsoft Windows Media Audio','audio/x-ms-wma','.wma','Wikipedia: Windows Media Audio'),
            new scUtils.MimeType('Real Audio Sound','audio/x-pn-realaudio','.ram','Wikipedia: RealPlayer'),
            new scUtils.MimeType('Real Audio Sound','audio/x-pn-realaudio-plugin','.rmp','Wikipedia: RealPlayer'),
            new scUtils.MimeType('Waveform Audio File Format (WAV)','audio/x-wav','.wav','Wikipedia: WAV')
        ];
        this.aVideo = [
            new scUtils.MimeType('3GP','video/3gpp','.3gp','Wikipedia: 3GP'),
            new scUtils.MimeType('3GP2','video/3gpp2','.3g2','Wikipedia: 3G2'),
            new scUtils.MimeType('H.261','video/h261','.h261','Wikipedia: H.261'),
            new scUtils.MimeType('H.263','video/h263','.h263','Wikipedia: H.263'),
            new scUtils.MimeType('H.264','video/h264','.h264','Wikipedia: H.264'),
            new scUtils.MimeType('JPGVideo','video/jpeg','.jpgv','RFC 3555'),
            new scUtils.MimeType('JPEG 2000 Compound Image File Format','video/jpm','.jpm','IANA: JPM'),
            new scUtils.MimeType('Motion JPEG 2000','video/mj2','.mj2','IANA: MJ2'),
            new scUtils.MimeType('MPEG-4 Video','video/mp4','.mp4','Wikipedia: MP4'),
            new scUtils.MimeType('MPEG Video','video/mpeg','.mpeg','Wikipedia: MPEG'),
            new scUtils.MimeType('Ogg Video','video/ogg','.ogv','Wikipedia: Ogg'),
            new scUtils.MimeType('Quicktime Video','video/quicktime','.qt','Wikipedia: Quicktime'),
            new scUtils.MimeType('DECE High Definition Video','video/vnd.dece.hd','.uvh','IANA: DECE HD Video'),
            new scUtils.MimeType('DECE Mobile Video','video/vnd.dece.mobile','.uvm','IANA: DECE Mobile Video'),
            new scUtils.MimeType('DECE PD Video','video/vnd.dece.pd','.uvp','IANA: DECE PD Video'),
            new scUtils.MimeType('DECE SD Video','video/vnd.dece.sd','.uvs','IANA: DECE SD Video'),
            new scUtils.MimeType('DECE Video','video/vnd.dece.video','.uvv','IANA: DECE Video'),
            new scUtils.MimeType('FAST Search & Transfer ASA','video/vnd.fvt','.fvt','IANA: FVT'),
            new scUtils.MimeType('MPEG Url','video/vnd.mpegurl','.mxu','IANA: MPEG Url'),
            new scUtils.MimeType('Microsoft PlayReady Ecosystem Video','video/vnd.ms-playready.media.pyv','.pyv','IANA: Microsoft PlayReady Ecosystem'),
            new scUtils.MimeType('DECE MP4','video/vnd.uvvu.mp4','.uvu','IANA: DECE MP4'),
            new scUtils.MimeType('Vivo','video/vnd.vivo','.viv','IANA: Vivo'),
            new scUtils.MimeType('Open Web Media Project - Video','video/webm','.webm','WebM Project'),
            new scUtils.MimeType('Flash Video','video/x-f4v','.f4v','Wikipedia: Flash Video'),
            new scUtils.MimeType('FLI/FLC Animation Format','video/x-fli','.fli','FLI/FLC Animation Format'),
            new scUtils.MimeType('Flash Video','video/x-flv','.flv','Wikipedia: Flash Video'),
            new scUtils.MimeType('M4v','video/x-m4v','.m4v','Wikipedia: M4v'),
            new scUtils.MimeType('Microsoft Advanced Systems Format (ASF)','video/x-ms-asf','.asf','Wikipedia: Advanced Systems Format (ASF)'),
            new scUtils.MimeType('Microsoft Windows Media','video/x-ms-wm','.wm','Wikipedia: Advanced Systems Format (ASF)'),
            new scUtils.MimeType('Microsoft Windows Media Video','video/x-ms-wmv','.wmv','Wikipedia: Advanced Systems Format (ASF)'),
            new scUtils.MimeType('Microsoft Windows Media Audio/Video Playlist','video/x-ms-wmx','.wmx','Wikipedia: Advanced Systems Format (ASF)'),
            new scUtils.MimeType('Microsoft Windows Media Video Playlist','video/x-ms-wvx','.wvx','Wikipedia: Advanced Systems Format (ASF)'),
            new scUtils.MimeType('Audio Video Interleave (AVI)','video/x-msvideo','.avi','Wikipedia: AVI'),
            new scUtils.MimeType('SGI Movie','video/x-sgi-movie','.movie','SGI Facts')
        ];

        this.aCategories = [ 'images', 'text', 'application', 'audio', 'video' ];
    }

    scUtils.MimeTypes.prototype.toMapByMime = function( aMimeType ){
        if( aMimeType instanceof Array === false ) return {};
        var map = {};
        for( var i=0, l=aMimeType.length,itm=null; i<l; i++ ){
            itm = aMimeType[i];
            map[itm.sMimeType] = itm;
        }
        return map;
    }

    scUtils.MimeTypes.prototype.getMimeMap = function( sCategory ){
        sCategory = sCategory.toLowerCase();
        switch( sCategory ){
            case 'audio':
            case 'aaudio':
                if( this.oAudio ) return this.oAudio;
                return this.oAudio = this.toMapByMime( this.aAudio );
            case 'aimage':
            case 'image':
            case 'images':
            case 'aimages':
            case 'img':
            case 'imgs':
                if( this.oImages ) return this.oImages;
                return this.oImages = this.toMapByMime( this.aImages );
            case 'aapplication':
            case 'application':
            case 'app':
                if( this.oApplication ) return this.oApplication;
                return this.oApplication = this.toMapByMime( this.aApplication );
            case 'txt':
            case 'text':
            case 'atext':
                if( this.oText ) return this.oText;
                return this.oText = this.toMapByMime( this.aText );
            case 'video':
            case 'avideo':
            case 'vid':
                if( this.oVideo ) return this.oVideo;
                return this.oVideo = this.toMapByMime( this.aVideo );
            default:
                return {};
        }
    }
    
    scUtils.MimeTypes.prototype.isMimeType = function( sCategory, sMimeType ){
        //If they gave a Mimetype then sCategory is required
        if( sMimeType ){
            var map = this.getMimeMap(sCategory);
            return map[sMimeType] ? true : false;
        //They only gave a MimeType
        }else{
            sMimeType = sCategory;
            for( var i=0, l=this.aCategories.length,map=null; i<l; i++ ){
                map = this.getMimeMap( this.aCategories[i] );
                if( map[sMimeType] ){
                    return true;
                }
            }
        }
        return false;
    }

    scUtils.MimeTypes.prototype.isImageMimeType = function( sMimeType ){
        return this.isMimeType('image',sMimeType);
    }

    scUtils.MimeTypes.prototype.isAudioMimeType = function( sMimeType ){
        return this.isMimeType('audio',sMimeType);
    }

    scUtils.MimeTypes.prototype.isTextMimeType = function( sMimeType ){
        return this.isMimeType('text',sMimeType);
    }

    scUtils.MimeTypes.prototype.isApplicationMimeType = function( sMimeType ){
        return this.isMimeType('app',sMimeType);
    }

    scUtils.MimeTypes.prototype.isVideoMimeType = function( sMimeType ){
        return this.isMimeType('vid',sMimeType);
    }
}(scUtils);
